-- Care Guides reference content
-- Run this once in the Supabase SQL Editor, after schema.sql.

create table public.care_guides (
  id uuid primary key default gen_random_uuid(),
  species_type text not null check (species_type in ('dog', 'cat', 'small_animal', 'reptile', 'fish')),
  name text not null,
  lifespan text,
  temp text,
  humidity text,
  enclosure_size text,
  diet text,
  note text,
  created_at timestamptz not null default now()
);

-- Reference content, same for every user: readable by any signed-in user,
-- writable only from the Supabase dashboard (no insert/update/delete policy).
alter table public.care_guides enable row level security;

create policy "care_guides: readable by any signed-in user" on public.care_guides
  for select using (auth.role() = 'authenticated');

insert into public.care_guides (species_type, name, lifespan, temp, humidity, enclosure_size, diet, note) values
  ('dog', 'Dogs (general care)', '~10–13 yrs (varies by breed)', 'Comfortable indoor range; avoid heat/cold extremes outdoors', 'Not a primary factor', 'No enclosure — needs a yard/walks and daily exercise', 'Age-appropriate commercial dog food, consistent schedule', 'Core vaccinations, regular vet checkups, and mental stimulation (training, puzzle toys) matter as much as exercise.'),
  ('cat', 'Cats (general care)', '12–18 yrs, often longer indoors', 'Comfortable indoor range', 'Not a primary factor', 'No enclosure — indoor vertical space (shelves/trees) recommended', 'Age-appropriate commercial cat food, fresh water daily', 'Litter box scooped daily, scratching outlets, regular vet checkups. Indoor cats live longer, safer lives.'),
  ('small_animal', 'Rabbit', '8–12 yrs', 'Cool–room temp; heat-sensitive above ~80°F', 'Not a primary factor', '8+ sq ft pen/hutch plus daily exercise time', '~80% hay, fresh greens, small amount of pellets', 'Litter-trainable; teeth grow continuously, needs constant chew material.'),
  ('small_animal', 'Guinea pig', '5–7 yrs', '65–75°F, avoid drafts/heat', '40–60%', '7.5+ sq ft for a pair', 'Hay-based + daily vitamin C via veggies/fortified pellets', 'Social — keep same-sex pairs/groups; skittish, benefits from hides.'),
  ('small_animal', 'Hamster', '2–3 yrs', '65–75°F', '40–60%', '24×12 in+ footprint, deep bedding for burrowing', 'Seed/pellet mix + occasional veggies', 'Solitary — house alone; nocturnal, most active at night.'),
  ('small_animal', 'Gerbil', '2–4 yrs', '65–75°F', 'Low–moderate; avoid damp bedding', 'Deep bedding for burrowing/tunneling', 'Low-moisture seed mix, hay, occasional veggies', 'Social — same-sex pairs from a young age; very active, needs a wheel.'),
  ('small_animal', 'Rat', '2–3 yrs', '65–75°F', '40–60%', 'Multi-level cage with climbing/enrichment', 'Omnivorous lab block diet + fresh food', 'Very social — always keep in pairs/groups; prone to respiratory issues, needs good ventilation.'),
  ('small_animal', 'Mouse', '1.5–2.5 yrs', '65–75°F', '40–60%', 'Small but needs a wheel + chew toys', 'Seed/pellet diet', 'Social in same-sex groups (females easier); strong odor, needs frequent cleaning.'),
  ('small_animal', 'Chinchilla', '10–15 yrs', 'Below 75°F — overheats easily', 'Low, ~30–40%; dust baths (not water) a few times a week', 'Tall cage, very active — needs room to jump', 'Hay-based, chinchilla-specific pellets, minimal treats', 'Longest-lived of the small animals; very active.'),
  ('small_animal', 'Ferret', '6–8 yrs', '60–75°F', 'Not a primary factor', 'Multi-level cage + daily out-of-cage time', 'High-protein, high-fat ferret-specific food (obligate carnivore)', 'Very playful; musky odor is natural even if descented.'),
  ('small_animal', 'Hedgehog', '4–6 yrs', '68–80°F — needs supplemental heat or risks hibernation attempt', 'Low–moderate', 'Solid-floor enclosure, solitary housing', 'High-quality cat/hedgehog food + mealworms (insectivore-leaning)', 'Solitary — don''t house together; nocturnal, may be prickly at first.'),
  ('small_animal', 'Sugar glider', '10–15 yrs', '65–80°F', 'Moderate, ~40–60%', 'Tall cage with branches — arboreal', 'Omnivorous; careful calcium:phosphorus balance needed', 'Highly social — never keep alone; nocturnal.'),
  ('small_animal', 'Degu', '6–9 yrs', '65–75°F', 'Low, ~30–40%; dust baths like chinchillas', 'Large cage, big exercise wheel', 'Low-sugar — timothy hay, chinchilla/degu pellets, no sugary fruit', 'Social, diabetes-prone; very vocal and active.'),
  ('small_animal', 'Chipmunk', '5–10 yrs in captivity', 'Room temp; tolerates cooler ranges', 'Not a primary factor', 'Large, secure, multi-level — natural escape artists', 'Omnivorous — nuts, seeds, occasional protein', 'Not commonly domesticated; can be flighty with handling.'),
  ('small_animal', 'Prairie dog', '8–10 yrs', 'Room temp', 'Not a primary factor', 'Large space to dig, best in bonded pairs/groups', 'Hay-based herbivore diet, no sugary treats', 'Highly social burrowing animal; can be destructive without socialization.'),
  ('small_animal', 'Skunk', '10–15 yrs', 'Room temp', 'Not a primary factor', 'Secure, enriched indoor space', 'Omnivorous — mix of cat food and produce', 'Check local laws — illegal to own in many places; often nocturnal, strong-willed.'),
  ('small_animal', 'Short-tailed opossum', '~4 yrs', '75–80°F', 'Moderate', 'Solitary housing — territorial', 'Protein-rich — insects, lean meat, plus some fruit', 'Nocturnal insectivore/omnivore.'),
  ('small_animal', 'Flying squirrel', '10–15 yrs', '65–80°F', 'Moderate', 'Tall cage for climbing/gliding', 'Omnivorous; calcium balance similar to sugar gliders', 'Highly social — best kept in pairs/groups; nocturnal.'),
  ('reptile', 'Bearded dragon', '8–12 yrs', 'Basking 95–110°F, cool side ~75–85°F', '30–40%', '40+ gal for an adult', 'Omnivorous — insects + leafy greens, more plant matter with age', 'Needs UVB lighting.'),
  ('reptile', 'Leopard gecko', '15–20 yrs', 'Warm side 88–92°F', '30–40%, higher in moist hide', '20 gal long for one adult', 'Insectivore — crickets/mealworms dusted with calcium', 'Nocturnal; low UVB now often recommended though not strictly required.'),
  ('reptile', 'Ball python', '20–30 yrs', 'Warm side 88–92°F, ambient 78–80°F', '50–60%', '40+ gal for an adult; tight hides preferred', 'Appropriately sized rodents every 1–2 weeks', 'Secretive/burrowing; can go off food during shedding or stress.'),
  ('reptile', 'Corn snake', '15–20 yrs', '78–85°F warm side', '40–50%', '20+ gal, secure lid essential', 'Appropriately sized mice on a regular schedule', 'Hardy, easygoing beginner snake; strong escape artist.'),
  ('reptile', 'Crested gecko', '15–20 yrs', '72–78°F, no strong heating usually needed', '60–80%', '18×18×24 in tall, planted, arboreal', 'Commercial crested gecko diet + occasional live insects', 'Does well at room temperature.'),
  ('reptile', 'Red-eared slider', '20–30+ yrs', 'Water 75–78°F, basking 90–95°F', 'N/A — aquatic', '75+ gal for an adult, deep water + basking dock', 'Omnivorous, more carnivorous when young', 'UVB essential; grows large, often outgrows starter setups.'),
  ('reptile', 'Box turtle', '25–50+ yrs', '75–85°F, basking ~90°F', '60–80%', 'Large enclosure or secure outdoor pen', 'Omnivorous — protein, veggies, occasional fruit', 'Many regions require a permit; UVB needed if kept indoors.'),
  ('reptile', 'Blue-tongued skink', '15–20 yrs', 'Basking 95–100°F, ambient 75–85°F', '40–60%', '40+ gal for an adult', 'Omnivorous — roughly half protein, half veggies/fruit', 'Generally docile, one of the calmer lizard pets.'),
  ('reptile', 'Russian tortoise', '40–50+ yrs', '75–85°F, basking ~95°F', '30–50%', 'Large, dry enclosure with burrowing substrate', 'Herbivorous — leafy greens/weeds, avoid high-protein/fruit', 'Needs UVB; a serious long-term commitment given lifespan.'),
  ('reptile', 'Sulcata tortoise', '70+ yrs', '80–90°F, basking ~95°F', '30–50%', 'Substantial outdoor space as an adult (100+ lbs)', 'High-fiber, low-protein herbivorous diet', 'One of the largest tortoise species; not suited to indoor-only keeping long-term.'),
  ('reptile', 'Green anole', '3–6 yrs', 'Basking 85–90°F', '50–70%', 'Tall, planted enclosure — arboreal', 'Insectivore — small crickets/fruit flies', 'Changes color based on mood/temperature, not true camouflage.'),
  ('reptile', 'Veiled chameleon', '5–8 yrs', 'Basking 85–95°F, ambient 72–80°F', '50–70%, daily misting/dripper', 'Tall, well-ventilated screen enclosure', 'Insectivore — gut-loaded, dusted feeder insects', 'Solitary and stress-sensitive — never house two together.'),
  ('reptile', 'King snake', '15–20 yrs', '75–85°F', '40–50%', '20+ gal, multiple hides', 'Appropriately sized rodents', 'Hardy beginner snake; never house with other snakes.'),
  ('reptile', 'Milk snake', '15–20 yrs', '75–85°F', '40–50%', '20+ gal, multiple hides', 'Appropriately sized mice', 'Secretive; similar care to king snakes.'),
  ('reptile', 'Boa constrictor', '20–30 yrs', 'Warm side 80–85°F', '50–60%', 'Substantial as an adult — often 6–8+ ft long', 'Appropriately sized rodents/rabbits on a regular schedule', 'Often docile but needs experienced, confident handling given size.'),
  ('reptile', 'Uromastyx', '15–20 yrs', 'Basking 110–120°F', 'Low, 10–30% — desert species', '40+ gal, dry substrate', 'Primarily herbivorous — leafy greens, seeds, legumes; low-water', 'Minimal to no reliance on insects, unlike most lizards.'),
  ('reptile', 'Gargoyle gecko', '15–20 yrs', '72–78°F, no strong heating usually needed', '60–80%', '18×18×24 in tall, arboreal', 'Commercial gecko diet + occasional insects', 'Similar husbandry to crested geckos; nocturnal.'),
  ('reptile', 'Green iguana', '15–20 yrs', 'Basking 95°F, ambient 80–85°F', '60–70%', 'Very large, tall — adults reach 5–6 ft', 'Strictly herbivorous — no animal protein', 'Strong UVB needed; can become strong and assertive.'),
  ('reptile', 'Chinese water dragon', '10–15 yrs', 'Basking 90–95°F, ambient 78–80°F', '70–80%', 'Large, with both water for soaking and climbing branches', 'Omnivorous — insects plus some veggies/fruit', 'Can be flighty; prone to nose-rubbing in too-small enclosures.'),
  ('reptile', 'Savannah monitor', '10–15 yrs', 'Basking 100°F+, ambient 85°F', '40–60%', 'Large, substantial as an adult', 'Primarily insectivore/carnivore — feed carefully to avoid obesity', 'Powerful; benefits from confident, regular handling.'),
  ('reptile', 'Garter snake', '6–10 yrs', '70–80°F', '40–60%', '10–20 gal', 'Fish, worms, and other appropriately sized prey (not just rodents)', 'Beginner-friendly, smaller than many colubrids; active and diurnal.'),
  ('fish', 'Angelfish', '~10 yrs', '76–82°F', 'N/A — aquatic', '29+ gal, tall tank', 'Omnivorous flake/pellet + occasional live/frozen food', 'Semi-aggressive, can be fin-nippy as adults.'),
  ('fish', 'Betta', '2–4 yrs', '76–80°F', 'N/A — aquatic', '5+ gal, heated, one male only', 'Carnivorous pellet diet', 'Males are territorial — never house two males together.'),
  ('fish', 'Bristlenose pleco', '5–10 yrs', '73–81°F', 'N/A — aquatic', '25+ gal with driftwood', 'Algae wafers + driftwood to graze', 'Peaceful bottom-dweller, stays smaller than common plecos.'),
  ('fish', 'Butterflyfish', '5–7 yrs', '72–78°F (marine)', 'N/A — aquatic', '75+ gal reef or fish-only marine tank', 'Varies — many species are picky eaters', 'Some species nip at coral; challenging for beginners.'),
  ('fish', 'Cherry barb', '4–6 yrs', '73–81°F', 'N/A — aquatic', '20+ gal, school of 6+', 'Omnivorous flake diet', 'Easy for beginners; males color up bright red.'),
  ('fish', 'Clown loach', '10–15+ yrs', '75–85°F', 'N/A — aquatic', '75+ gal long-term (grows large)', 'Omnivorous, appreciates sinking foods', 'Social — keep in groups; can live decades.'),
  ('fish', 'Clownfish', '6–10 yrs', '74–79°F (marine)', 'N/A — aquatic', '20+ gal marine tank', 'Omnivorous marine flake/pellet', 'Hardy for a marine fish; anemone pairing not required.'),
  ('fish', 'Cory catfish', '~5 yrs', '72–78°F', 'N/A — aquatic', '20+ gal, group of 6+', 'Sinking pellets/wafers', 'Sensitive to poor water quality — a good indicator species.'),
  ('fish', 'Danio', '3–5 yrs', '64–74°F — tolerant of a range', 'N/A — aquatic', '20+ gal, school of 6+', 'Omnivorous flake diet', 'Very hardy and active; good beginner fish.'),
  ('fish', 'Discus', '10–15 yrs', '82–86°F — very sensitive to change', 'N/A — aquatic', '55+ gal, tall tank', 'Omnivorous, frequent water changes needed', 'Advanced-keeper fish; social, keep in groups.'),
  ('fish', 'Dwarf gourami', '4–6 yrs', '72–82°F', 'N/A — aquatic', '20+ gal', 'Omnivorous flake diet', 'Labyrinth fish (breathes surface air); source carefully, prone to a common viral disease.'),
  ('fish', 'Fancy goldfish', '10–15 yrs', '65–72°F, cold-water — no heater needed', 'N/A — aquatic', '20+ gal for one', 'Omnivorous, sinking/floating pellets', 'Produces a lot of waste — needs strong filtration.'),
  ('fish', 'Flowerhorn cichlid', '10–12 yrs', '78–85°F', 'N/A — aquatic', '75+ gal as an adult', 'Carnivorous, high-protein pellet diet', 'Hybrid cichlid, often kept alone due to aggression.'),
  ('fish', 'Gar (freshwater)', '15–20+ yrs', '70–80°F', 'N/A — aquatic', 'Large — many species need a pond, not a tank', 'Carnivorous, whole-prey/meaty diet', 'Grows large — research the specific species before buying.'),
  ('fish', 'Glass catfish', '5–8 yrs', '75–82°F', 'N/A — aquatic', '20+ gal, group of 6+', 'Peaceful omnivore, small sinking foods', 'Genuinely translucent body; sensitive to poor water quality.'),
  ('fish', 'Goby', '2–5 yrs', 'Varies by species', 'N/A — aquatic', 'Varies — check freshwater vs marine before buying', 'Varies, often small live/frozen foods', 'Many are small-territory bottom-dwellers.'),
  ('fish', 'Goldfish', '10–15+ yrs', '65–72°F, cold-water', 'N/A — aquatic', 'Large tank or pond long-term, not a bowl', 'Omnivorous flake/pellet', 'Grows larger than most expect; produces a lot of waste.'),
  ('fish', 'Guppy', '2–3 yrs', '72–82°F', 'N/A — aquatic', '10+ gal', 'Omnivorous flake diet', 'Live-bearer — breeds readily if males/females kept together.'),
  ('fish', 'Killifish', '2–5 yrs', 'Varies, often 72–78°F', 'N/A — aquatic', '10+ gal, species-dependent', 'Carnivorous, small live/frozen foods preferred', 'Some species are seasonal "annuals" with naturally short lives.'),
  ('fish', 'Koi', '25–35+ yrs', 'Cold-water pond fish', 'N/A — aquatic', 'Substantial outdoor pond, not an indoor tank', 'Omnivorous pellet diet', 'Grows large (12–24+ in); a pond-scale commitment.'),
  ('fish', 'Kuhli loach', '~10 yrs', '75–86°F', 'N/A — aquatic', '20+ gal, soft substrate, group', 'Sinking omnivorous foods', 'Eel-like, nocturnal and secretive.'),
  ('fish', 'Lionfish', '10–15 yrs', '72–79°F (marine)', 'N/A — aquatic', '75+ gal marine tank', 'Predatory — live or trained-to-frozen fish/shrimp', 'Venomous spines — handle maintenance carefully.'),
  ('fish', 'Mandarinfish', '2–4 yrs', '72–78°F (marine)', 'N/A — aquatic', '30+ gal, well-established reef', 'Live copepods — many won''t eat prepared food', 'Advanced fish despite small size.'),
  ('fish', 'Molly', '3–5 yrs', '72–78°F', 'N/A — aquatic', '10+ gal', 'Omnivorous flake + some algae/veggie matter', 'Live-bearer, easy beginner fish.'),
  ('fish', 'Neon tetra', '5–8 yrs', '70–81°F', 'N/A — aquatic', '10+ gal, school of 6+', 'Omnivorous micro-pellet/flake diet', 'Classic beginner schooling fish.'),
  ('fish', 'Oscar', '10–20 yrs', '74–81°F', 'N/A — aquatic', '55+ gal for one adult', 'Carnivorous pellet + occasional meaty foods', 'Grows large (12+ in); intelligent, recognizes owner.'),
  ('fish', 'Pearl gourami', '4–5 yrs', '77–82°F', 'N/A — aquatic', '30+ gal', 'Omnivorous flake diet', 'Peaceful labyrinth fish.'),
  ('fish', 'Pictus catfish', '~8 yrs', '75–81°F', 'N/A — aquatic', '55+ gal', 'Omnivorous sinking foods', 'Active at night; may eat very small tankmates.'),
  ('fish', 'Platy', '3–5 yrs', '70–77°F', 'N/A — aquatic', '10+ gal', 'Omnivorous flake diet', 'Live-bearer, very easy beginner fish.'),
  ('fish', 'Plecostomus (Pleco)', '10–15 yrs', '74–80°F', 'N/A — aquatic', '75+ gal long-term (common pleco grows to 18+ in)', 'Algae wafers + driftwood', 'Bristlenose is a smaller alternative if space is limited.'),
  ('fish', 'Puffer fish', '5–10 yrs', 'Varies by species, often 74–78°F', 'N/A — aquatic', 'Varies — check freshwater/brackish/marine before buying', 'Hard-shelled foods (snails) to wear down continuously growing teeth', 'Many species are semi-aggressive, poor community fish.'),
  ('fish', 'Rainbowfish', '5–8 yrs', '74–79°F', 'N/A — aquatic', '30+ gal, school of 6+', 'Omnivorous flake diet', 'Colors up best in a well-planted, well-lit tank.'),
  ('fish', 'Rasbora', '5–8 yrs', '72–81°F', 'N/A — aquatic', '10+ gal, school of 6+', 'Omnivorous micro-pellet/flake diet', 'Classic community-tank species alongside tetras.'),
  ('fish', 'Rope fish', '15–20 yrs', '75–82°F', 'N/A — aquatic', '30+ gal, tightly covered (skilled escape artist)', 'Peaceful but predatory toward very small tankmates', 'Eel-like, nocturnal, breathes surface air.'),
  ('fish', 'Rosy barb', '4–6 yrs', '64–72°F — tolerates cooler water', 'N/A — aquatic', '20+ gal, group of 5+', 'Omnivorous flake diet', 'Hardy schooling fish.'),
  ('fish', 'Seahorse', '1–5 yrs', 'Varies by species, often 72–75°F (marine)', 'N/A — aquatic', 'Species-only tank, stable conditions', 'Live or frozen food — slow feeder', 'Advanced-keeper fish; won''t compete well with faster fish.'),
  ('fish', 'Swordtail', '3–5 yrs', '72–79°F', 'N/A — aquatic', '15+ gal', 'Omnivorous flake diet', 'Live-bearer; males have a sword-like tail extension.'),
  ('fish', 'Tang', '5–8+ yrs', '72–78°F (marine)', 'N/A — aquatic', '100+ gal, strong swimming room', 'Herbivore-leaning — needs regular algae/seaweed', 'Can be aggressive toward similarly shaped tankmates.'),
  ('fish', 'Tetra', '3–5 yrs', '72–78°F', 'N/A — aquatic', '10+ gal, school of 6+', 'Omnivorous flake diet', 'Easy beginner fish across most tetra species.'),
  ('fish', 'Tiger barb', '5–7 yrs', '74–79°F', 'N/A — aquatic', '20+ gal, group of 6+', 'Omnivorous flake diet', 'Can nip fins if kept in too small a group.'),
  ('fish', 'Wrasse', '4–8 yrs', '72–78°F (marine)', 'N/A — aquatic', 'Varies widely by species', 'Varies — many help with pest control in reef tanks', 'Some bury in sand at night; research the specific species.');
